name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create tag
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/msmtp:${{env.tag}}
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USER}}/msmtp:${{env.tag}}
